Dollar = 2
Leverage = 10
TIME_PERIOD = "15m"
LIMIT = "1500"
TIME_SLEEP = 2
Dollars = Dollar * Leverage
above_or_below_wick = 0.1
fixed_stop_loss = 0.25
trailing_order_check = 1.2
trailing_order_increase = 0.2
max_take_profit_limit = 3
