Dollar = 15
Leverage = 1
TIME_PERIOD = "15m"
LIMIT = "1500"
TIME_SLEEP = 2
Dollars = Dollar * Leverage
above_or_below_wick = 0.1
above_or_below_wick_stop_loss = 2.5
trailing_order_check = 0.3
trailing_order_increase = 0.1
max_take_profit_limit = 20
